In [16]:
%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [17]:
import numpy as np
import numpy.linalg as lin
import matplotlib.pyplot as plt
import pandas as pd
import random
#   기본 모듈들을 불러와 줍니다

In [18]:
import preprocessing

In [19]:
data = np.array([
    [1,2],
    [3,3],
    [3,5],
    [5,4],
    [5,6],
    [6,5],
    [8,7],
    [9,8],
])

# temp = data[:, 1:2].copy()

In [20]:
# data[:, 1:2] = data[:, 0:1]
# data[:, 0:1] = temp
# data

In [21]:
scatter = 1/8 * preprocessing.get_scatter_matrix(data)
scatter

array([[6.25, 4.25],
       [4.25, 3.5 ]])

In [22]:
value, vector = preprocessing.get_eigen_vectors(scatter)

In [23]:
vector @ np.diag(value) @ vector.T

array([[6.25, 4.25],
       [4.25, 3.5 ]])

In [24]:
vector

array([[ 0.80864711, -0.58829402],
       [ 0.58829402,  0.80864711]])

In [28]:
a = preprocessing.PCA(data, vector, value)
#a(2)
a.reconstruct(1)

array([[0.95719265, 2.05884139],
       [2.7407352 , 3.35637577],
       [3.69217971, 4.04855548],
       [4.52427774, 4.65391014],
       [5.47572226, 5.34608986],
       [5.65391014, 5.47572226],
       [7.91317495, 7.11934649],
       [9.04280735, 7.94115861]])

In [11]:
from sklearn.decomposition import PCA
pca = PCA(n_components=2)

In [12]:
pca.fit_transform(data)

array([[ 4.99947049, -0.07276523],
       [ 2.79388226, -0.44070617],
       [ 1.61729421,  1.17658805],
       [ 0.58829402, -0.80864711],
       [-0.58829402,  0.80864711],
       [-0.80864711, -0.58829402],
       [-3.60252936, -0.14758786],
       [-4.99947049,  0.07276523]])

In [13]:
a.explained_variance_ratio

array([0.95814278, 0.04185722])

In [14]:
pca.explained_variance_ratio_

array([0.95814278, 0.04185722])

# 실제 데이터 사용해서 비교하기