# data load

In [52]:
import os

import cv2

path = "./data/faces"

tests = []
trains = []

data_lists = os.listdir(path)
data_dict = {}
for data in data_lists:
    files = os.listdir(f"{path}/{data}")
    file_list= []
    for file in files:
        file_path = f"{path}/{data}/{file}"
        file_list.append(file_path)
    data_dict["path"] = file_list
    data_dict['label'] = data

In [54]:
data_dict

{'path': ['./data/faces/s9/1.pgm',
  './data/faces/s9/10.pgm',
  './data/faces/s9/2.pgm',
  './data/faces/s9/3.pgm',
  './data/faces/s9/4.pgm',
  './data/faces/s9/5.pgm',
  './data/faces/s9/6.pgm',
  './data/faces/s9/7.pgm',
  './data/faces/s9/8.pgm',
  './data/faces/s9/9.pgm'],
 'label': 's9'}

In [49]:
import pandas as pd
import cv2
data = pd.DataFrame(data_dict)
data
# data = cv2.imread(data.s1[1])
# cv2.imshow("data", data)
# cv2.waitKey(0)
# cv2.destroyAllWindows()

s1                      s10                      s11  \
0    ./data/faces/s1/1.pgm   ./data/faces/s10/1.pgm   ./data/faces/s11/1.pgm   
1                       s1                      s10                      s11   
2   ./data/faces/s1/10.pgm  ./data/faces/s10/10.pgm  ./data/faces/s11/10.pgm   
3                       s1                      s10                      s11   
4    ./data/faces/s1/2.pgm   ./data/faces/s10/2.pgm   ./data/faces/s11/2.pgm   
5                       s1                      s10                      s11   
6    ./data/faces/s1/3.pgm   ./data/faces/s10/3.pgm   ./data/faces/s11/3.pgm   
7                       s1                      s10                      s11   
8    ./data/faces/s1/4.pgm   ./data/faces/s10/4.pgm   ./data/faces/s11/4.pgm   
9                       s1                      s10                      s11   
10   ./data/faces/s1/5.pgm   ./data/faces/s10/5.pgm   ./data/faces/s11/5.pgm   
11                      s1                      s10                      s11   
12   ./data/faces/s1/6.pgm   ./data/faces/s10/6.pgm   ./data/faces/s11/6.pgm   
13                      s1                      s10                      s11   
14   ./data/faces/s1/7.pgm   ./data/faces/s10/7.pgm   ./data/faces/s11/7.pgm   
15                      s1                      s10                      s11   
16   ./data/faces/s1/8.pgm   ./data/faces/s10/8.pgm   ./data/faces/s11/8.pgm   
17                      s1                      s10                      s11   
18   ./data/faces/s1/9.pgm   ./data/faces/s10/9.pgm   ./data/faces/s11/9.pgm   
19                      s1                      s10                      s11   

                        s12                      s13                      s14  \
0    ./data/faces/s12/1.pgm   ./data/faces/s13/1.pgm   ./data/faces/s14/1.pgm   
1                       s12                      s13                      s14   
2   ./data/faces/s12/10.pgm  ./data/faces/s13/10.pgm  ./data/faces/s14/10.pgm   
3                       s12                      s13                      s14   
4    ./data/faces/s12/2.pgm   ./data/faces/s13/2.pgm   ./data/faces/s14/2.pgm   
5                       s12                      s13                      s14   
6    ./data/faces/s12/3.pgm   ./data/faces/s13/3.pgm   ./data/faces/s14/3.pgm   
7                       s12                      s13                      s14   
8    ./data/faces/s12/4.pgm   ./data/faces/s13/4.pgm   ./data/faces/s14/4.pgm   
9                       s12                      s13                      s14   
10   ./data/faces/s12/5.pgm   ./data/faces/s13/5.pgm   ./data/faces/s14/5.pgm   
11                      s12                      s13                      s14   
12   ./data/faces/s12/6.pgm   ./data/faces/s13/6.pgm   ./data/faces/s14/6.pgm   
13                      s12                      s13                      s14   
14   ./data/faces/s12/7.pgm   ./data/faces/s13/7.pgm   ./data/faces/s14/7.pgm   
15                      s12                      s13                      s14   
16   ./data/faces/s12/8.pgm   ./data/faces/s13/8.pgm   ./data/faces/s14/8.pgm   
17                      s12                      s13                      s14   
18   ./data/faces/s12/9.pgm   ./data/faces/s13/9.pgm   ./data/faces/s14/9.pgm   
19                      s12                      s13                      s14   

                        s15                      s16                      s17  \
0    ./data/faces/s15/1.pgm   ./data/faces/s16/1.pgm   ./data/faces/s17/1.pgm   
1                       s15                      s16                      s17   
2   ./data/faces/s15/10.pgm  ./data/faces/s16/10.pgm  ./data/faces/s17/10.pgm   
3                       s15                      s16                      s17   
4    ./data/faces/s15/2.pgm   ./data/faces/s16/2.pgm   ./data/faces/s17/2.pgm   
5                       s15                      s16                      s17   
6    ./data/faces/s15/3.pgm   ./data/faces/s16/3.pgm   ./data/faces/s17/3.

In [36]:
data.shape

(112, 92, 3)

In [37]:
from sklearn.datasets import fetch_olivetti_faces

faces_all = fetch_olivetti_faces()
K = 20  # 20번 인물의 사진만 선택
faces = faces_all.images[faces_all.target == K]

# N = 2
# M = 5
# fig = plt.figure(figsize=(10, 5))
# plt.subplots_adjust(top=1, bottom=0, hspace=0, wspace=0.05)
# for i in range(N):
#     for j in range(M):
#         k = i * M + j
#         ax = fig.add_subplot(N, M, k+1)
#         ax.imshow(faces[k], cmap=plt.cm.bone)
#         ax.grid(False)
#         ax.xaxis.set_ticks([])
#         ax.yaxis.set_ticks([])
# plt.suptitle("올리베티 얼굴 사진")
# plt.tight_layout()
# plt.show()

downloading Olivetti faces from https://ndownloader.figshare.com/files/5976027 to C:\Users\a\scikit_learn_data


In [1]:

%load_ext autoreload
%autoreload 2

In [2]:
import numpy as np
import numpy.linalg as lin
import matplotlib.pyplot as plt
import pandas as pd
import random
#   기본 모듈들을 불러와 줍니다

In [3]:
import preprocessing

In [4]:
data = np.array([
    [1,2],
    [3,3],
    [3,5],
    [5,4],
    [5,6],
    [6,5],
    [8,7],
    [9,8],
])

# temp = data[:, 1:2].copy()

In [5]:
# data[:, 1:2] = data[:, 0:1]
# data[:, 0:1] = temp
# data

In [14]:
k = preprocessing.PCA(data)
print(k.get_scatter_matrix())

[[6.25 4.25]
 [4.25 3.5 ]]


In [15]:
k.fit(2)

In [17]:
print(k())

[[-4.99947049 -0.07276523]
 [-2.79388226 -0.44070617]
 [-1.61729421  1.17658805]
 [-0.58829402 -0.80864711]
 [ 0.58829402  0.80864711]
 [ 0.80864711 -0.58829402]
 [ 3.60252936 -0.14758786]
 [ 4.99947049  0.07276523]]


In [17]:
a = preprocessing.PCA(data, vector, value)
#a(2)
print(a.reconstruct(1))

[[0.95719265 2.05884139]
 [2.7407352  3.35637577]
 [3.69217971 4.04855548]
 [4.52427774 4.65391014]
 [5.47572226 5.34608986]
 [5.65391014 5.47572226]
 [7.91317495 7.11934649]
 [9.04280735 7.94115861]]


In [82]:
from sklearn.decomposition import PCA
pca = PCA(n_components=1)

In [83]:
pca.fit_transform(data)

array([[ 4.99947049],
       [ 2.79388226],
       [ 1.61729421],
       [ 0.58829402],
       [-0.58829402],
       [-0.80864711],
       [-3.60252936],
       [-4.99947049]])

In [14]:
a.explained_variance_ratio

array([0.95814278, 0.04185722])

In [15]:
pca.explained_variance_ratio_

array([0.95814278, 0.04185722])

# 실제 데이터 사용해서 비교하기

In [52]:
# 1. Normalization
def normalize(X):
    N, D = X.shape
    mu = np.mean(X, axis=0)
    Xbar = X - mu
    return Xbar, mu


# 2. Covariance matrix 의 eigenvalue, eigenvector 계산
def eig(S):
    eig_vals, eig_vecs = np.linalg.eig(S)
    sort_indices = np.argsort(eig_vals)[::-1] # 내림차순 정렬
    return eig_vals[sort_indices], eig_vecs[:, sort_indices]


# 3. Principal components 에 해당하는 각 벡터의 기저공간에 데이터 사영
def reconstruct(X, PC):
    return (X @ PC) @ PC.T # vector projection 참고


# PCA 알고리즘
def PCA2(images, num_components, num_data=1000):
    X = images[:num_data]
    N, D = X.shape

    # 1. Normalization
    X_normalized, mean = normalize(X)

    # 2. Covariance matrix 의 eigenvalue, eigenvector 계산
    S = (X_normalized.T @ X_normalized) / N
    eig_vals, eig_vecs = eig(S)

    # 3. Principal components 에 해당하는 각 벡터의 기저공간에 데이터 사영
    principal_vals, principal_components = np.real(eig_vals[:num_components]), np.real(eig_vecs[:,:num_components])
    print(X_normalized @ principal_components)
    reconst_X = reconstruct(X_normalized, principal_components) + mean
    return reconst_X, mean, principal_vals, principal_components



In [64]:
PCA2(data, 1)

[[-4.99947049]
 [-2.79388226]
 [-1.61729421]
 [-0.58829402]
 [ 0.58829402]
 [ 0.80864711]
 [ 3.60252936]
 [ 4.99947049]]


(array([[0.95719265, 2.05884139],
        [2.7407352 , 3.35637577],
        [3.69217971, 4.04855548],
        [4.52427774, 4.65391014],
        [5.47572226, 5.34608986],
        [5.65391014, 5.47572226],
        [7.91317495, 7.11934649],
        [9.04280735, 7.94115861]]),
 array([5., 5.]),
 array([9.3418921]),
 array([[0.80864711],
        [0.58829402]]))

In [77]:
k = preprocessing.PCA(data)
print(k.get_scatter_matrix())

[[6.25 4.25]
 [4.25 3.5 ]]
