In [149]:
import cv2
import os
import numpy as np

In [150]:
%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


# LDA Start

# Data preprocessing

In [151]:
label_encode_dict = {}
label_decode_dict = {}

for i in range(1, 41):
    label_encode_dict[i] = f"S{i}"
    
for i in range(1, 41):
    label_decode_dict[f"s{i}"] = i

In [152]:
import os
def load_images_from_folder(folder, label , width, height):
    images = []
    labels = []
    for filename in os.listdir(folder):

        img_path = os.path.join(folder, filename)
        if os.path.isfile(img_path):
            img = cv2.imread(img_path, cv2.IMREAD_GRAYSCALE)
            img = cv2.resize(img, (width, height))

            if img is not None:
                images.append(img.reshape(1,-1))
                labels.append(label_decode_dict[label])
    return images, labels


In [153]:
train_folder = './data/faces'
# test_folder = './data/faces/testing'


# Training 데이터 불러오기
train_images = []
train_label = []

print()
for folder in sorted(os.listdir(train_folder)):
    path = os.path.join(train_folder, folder)
    if os.path.isdir(path):
        images, labels = load_images_from_folder(path, folder, 64, 64)
        train_images.append(np.concatenate(images))
        train_label.append(labels)


# 넘파이 배열로 변환
train_data = np.concatenate(train_images)
train_label = np.array(train_label).reshape(-1)
#

print("Training 데이터 shape:", train_data.shape)
print("Training 정답 shape:", train_label.shape)

# print("Testing 데이터 shape:", test_data.shape)



Training 데이터 shape: (400, 4096)
Training 정답 shape: (400,)


# LDA 시작

In [159]:
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis

lda = LinearDiscriminantAnalysis(n_components=1)

lda.fit(train_data, train_label)
iris_lda = lda.transform(train_data)

In [156]:
iris_lda

array([[ -3.20369148],
       [ -5.10784797],
       [ -4.93384901],
       [ -6.70895127],
       [ -5.72474286],
       [ -5.63049779],
       [ -4.39869114],
       [ -3.75426838],
       [ -5.39364361],
       [ -5.57378215],
       [ -3.24629663],
       [ -4.88728242],
       [ -2.83645139],
       [ -1.77603982],
       [ -2.07215284],
       [ -3.91107017],
       [ -2.65172573],
       [ -2.25111361],
       [ -2.68952151],
       [ -2.35030268],
       [  1.55058661],
       [  1.43179781],
       [  0.74930032],
       [  1.02786251],
       [ -0.17489074],
       [  0.86094876],
       [  1.37071491],
       [  0.35251006],
       [  1.13142403],
       [  0.15041262],
       [-10.10248947],
       [-10.4342716 ],
       [-10.21082174],
       [-10.33360664],
       [ -9.23439267],
       [-10.10064244],
       [ -9.72233341],
       [-10.73990968],
       [ -9.38343284],
       [-10.47201871],
       [ -6.62291318],
       [ -7.85052052],
       [ -7.60813427],
       [ -8

In [129]:
lda.scalings_

array([[ 3.43848401e-04, -2.39620926e-04, -2.44800615e-04, ...,
         4.36872455e-05,  2.09248951e-03, -8.09679205e-04],
       [ 4.45188470e-04, -1.58737231e-03,  7.62357864e-04, ...,
        -4.38763327e-04,  1.05376417e-03,  1.14020794e-06],
       [ 4.15890553e-04, -1.37256337e-03,  1.06001356e-03, ...,
        -1.01373935e-04,  6.59298842e-04, -4.24523816e-04],
       ...,
       [ 1.01524736e-03,  4.00288327e-04,  2.18089347e-04, ...,
         1.02854939e-04,  8.81091460e-04,  1.25692025e-04],
       [ 7.64135992e-04,  1.35031726e-04,  9.03979000e-04, ...,
        -7.91538016e-05, -2.44689678e-04, -3.75848215e-04],
       [ 1.13313307e-03,  6.47908991e-04,  9.43306348e-04, ...,
        -7.84356793e-04, -1.24807042e-03, -1.80560998e-05]])

In [130]:
iris_lda[train_label == 0]

array([], shape=(0, 1), dtype=float64)

In [131]:
from preprocessing import LDA

In [132]:
print(train_label.reshape(-1))

[ 1  1  1  1  1  1  1  1  1  1 10 10 10 10 10 10 10 10 10 10 11 11 11 11
 11 11 11 11 11 11 12 12 12 12 12 12 12 12 12 12 13 13 13 13 13 13 13 13
 13 13 14 14 14 14 14 14 14 14 14 14 15 15 15 15 15 15 15 15 15 15 16 16
 16 16 16 16 16 16 16 16 17 17 17 17 17 17 17 17 17 17 18 18 18 18 18 18
 18 18 18 18 19 19 19 19 19 19 19 19 19 19  2  2  2  2  2  2  2  2  2  2
 20 20 20 20 20 20 20 20 20 20 21 21 21 21 21 21 21 21 21 21 22 22 22 22
 22 22 22 22 22 22 23 23 23 23 23 23 23 23 23 23 24 24 24 24 24 24 24 24
 24 24 25 25 25 25 25 25 25 25 25 25 26 26 26 26 26 26 26 26 26 26 27 27
 27 27 27 27 27 27 27 27 28 28 28 28 28 28 28 28 28 28 29 29 29 29 29 29
 29 29 29 29  3  3  3  3  3  3  3  3  3  3 30 30 30 30 30 30 30 30 30 30
 31 31 31 31 31 31 31 31 31 31 32 32 32 32 32 32 32 32 32 32 33 33 33 33
 33 33 33 33 33 33 34 34 34 34 34 34 34 34 34 34 35 35 35 35 35 35 35 35
 35 35 36 36 36 36 36 36 36 36 36 36 37 37 37 37 37 37 37 37 37 37 38 38
 38 38 38 38 38 38 38 38 39 39 39 39 39 39 39 39 39

In [133]:
l = LDA(train_data, train_label.reshape(-1))

[ 1  1  1  1  1  1  1  1  1  1 10 10 10 10 10 10 10 10 10 10 11 11 11 11
 11 11 11 11 11 11 12 12 12 12 12 12 12 12 12 12 13 13 13 13 13 13 13 13
 13 13 14 14 14 14 14 14 14 14 14 14 15 15 15 15 15 15 15 15 15 15 16 16
 16 16 16 16 16 16 16 16 17 17 17 17 17 17 17 17 17 17 18 18 18 18 18 18
 18 18 18 18 19 19 19 19 19 19 19 19 19 19  2  2  2  2  2  2  2  2  2  2
 20 20 20 20 20 20 20 20 20 20 21 21 21 21 21 21 21 21 21 21 22 22 22 22
 22 22 22 22 22 22 23 23 23 23 23 23 23 23 23 23 24 24 24 24 24 24 24 24
 24 24 25 25 25 25 25 25 25 25 25 25 26 26 26 26 26 26 26 26 26 26 27 27
 27 27 27 27 27 27 27 27 28 28 28 28 28 28 28 28 28 28 29 29 29 29 29 29
 29 29 29 29  3  3  3  3  3  3  3  3  3  3 30 30 30 30 30 30 30 30 30 30
 31 31 31 31 31 31 31 31 31 31 32 32 32 32 32 32 32 32 32 32 33 33 33 33
 33 33 33 33 33 33 34 34 34 34 34 34 34 34 34 34 35 35 35 35 35 35 35 35
 35 35 36 36 36 36 36 36 36 36 36 36 37 37 37 37 37 37 37 37 37 37 38 38
 38 38 38 38 38 38 38 38 39 39 39 39 39 39 39 39 39

In [137]:
l.fit(1)

In [136]:
l()

array([[-20.12318323,   0.58384591,   2.27467622],
       [-20.12318323,   0.58384591,   2.27467622],
       [-20.12318323,   0.58384591,   2.27467622],
       ...,
       [-40.8183916 ,   6.29161461,   7.93767876],
       [-40.8183916 ,   6.29161461,   7.93767876],
       [-40.8183916 ,   6.29161461,   7.93767876]])

In [141]:
l.vector

array([[ 0.03366863],
       [ 0.06594577],
       [-0.0220669 ],
       ...,
       [-0.00955227],
       [-0.00886003],
       [-0.00471905]])

In [146]:
train_data

array([[ 47,  45,  47, ...,  44,  46,  46],
       [ 34,  32,  34, ...,  36,  38,  36],
       [ 60,  61,  56, ...,  36,  34,  33],
       ...,
       [112, 113, 113, ...,  88,  92,  92],
       [112, 112, 111, ...,  80,  88,  90],
       [110, 113, 110, ...,  89,  89,  89]], dtype=uint8)

In [147]:
train_data @ lda.scalings_[:, 0]
# lda.coef_

array([-30.67678044, -32.58093693, -32.40693798, -34.18204023,
       -33.19783182, -33.10358675, -31.8717801 , -31.22735734,
       -32.86673257, -33.04687111, -30.71938559, -32.36037139,
       -30.30954035, -29.24912878, -29.54524181, -31.38415913,
       -30.12481469, -29.72420257, -30.16261047, -29.82339164,
       -25.92250235, -26.04129116, -26.72378864, -26.44522645,
       -27.6479797 , -26.6121402 , -26.10237406, -27.12057891,
       -26.34166493, -27.32267635, -37.57557843, -37.90736056,
       -37.6839107 , -37.8066956 , -36.70748164, -37.5737314 ,
       -37.19542237, -38.21299864, -36.8565218 , -37.94510767,
       -34.09600214, -35.32360948, -35.08122323, -36.21975074,
       -33.51882559, -32.60175723, -33.83623347, -33.86632342,
       -34.43292701, -34.86030497, -28.76910282, -26.82964189,
       -28.42663737, -27.69866548, -30.01186158, -26.34029542,
       -28.68582387, -27.61915064, -28.28279656, -28.31384726,
       -25.32579465, -23.07490783, -24.58326923, -24.93

In [148]:
iris_lda

array([[ -3.20369148],
       [ -5.10784797],
       [ -4.93384901],
       [ -6.70895127],
       [ -5.72474286],
       [ -5.63049779],
       [ -4.39869114],
       [ -3.75426838],
       [ -5.39364361],
       [ -5.57378215],
       [ -3.24629663],
       [ -4.88728242],
       [ -2.83645139],
       [ -1.77603982],
       [ -2.07215284],
       [ -3.91107017],
       [ -2.65172573],
       [ -2.25111361],
       [ -2.68952151],
       [ -2.35030268],
       [  1.55058661],
       [  1.43179781],
       [  0.74930032],
       [  1.02786251],
       [ -0.17489074],
       [  0.86094876],
       [  1.37071491],
       [  0.35251006],
       [  1.13142403],
       [  0.15041262],
       [-10.10248947],
       [-10.4342716 ],
       [-10.21082174],
       [-10.33360664],
       [ -9.23439267],
       [-10.10064244],
       [ -9.72233341],
       [-10.73990968],
       [ -9.38343284],
       [-10.47201871],
       [ -6.62291318],
       [ -7.85052052],
       [ -7.60813427],
       [ -8