In [3]:
import cv2
import os
import numpy as np

# LDA Start

# Data preprocessing

In [4]:
img = cv2.imread("data/faces/testing/s5/1.pgm", cv2.IMREAD_UNCHANGED)

In [5]:
cv2.imshow("test", img)
cv2.waitKey()
cv2.destroyAllWindows()

In [6]:
label_dict = {}
for i in range(1, 41):
    label_dict[i] = f"S{i}"

In [7]:
import os
def load_images_from_folder(folder, label , width, height):
    images = []
    labels = []
    for filename in os.listdir(folder):

        img_path = os.path.join(folder, filename)
        if os.path.isfile(img_path):
            img = cv2.imread(img_path, cv2.IMREAD_GRAYSCALE)
            img = cv2.resize(img, (width, height))

            if img is not None:
                images.append(img.reshape(1,-1))
                labels.append(label)
    return images, labels


In [8]:
train_folder = 'data/faces/training'
test_folder = 'data/faces/testing'


# Training 데이터 불러오기
train_images = []
train_label = []

print()
for folder in sorted(os.listdir(train_folder)):
    path = os.path.join(train_folder, folder)
    if os.path.isdir(path):
        images,labels = load_images_from_folder(path, folder, 64, 64)
        train_images.append(np.concatenate(images))
        train_label.append(labels)

# Testing 데이터 불러오기
# test_images = []
# for subfolder in os.listdir(test_folder):
#     subfolder_path = os.path.join(test_folder, subfolder)
#     if os.path.isdir(subfolder_path):
#         images = load_images_from_folder(subfolder_path)
#         test_images.extend(images)

# 넘파이 배열로 변환
train_data = np.concatenate(train_images)
train_label = np.array(train_label).reshape(-1, 1)
# test_data = np.array(test_images)
#

print("Training 데이터 shape:", train_data.shape)
print("Training 정답 shape:", train_label.shape)

# print("Testing 데이터 shape:", test_data.shape)



Training 데이터 shape: (370, 4096)
Training 정답 shape: (370, 1)


# LDA 시작

In [9]:
from preprocessing import LDA

In [10]:
data = train_data.reshape(37, 10, -1)

In [11]:
l = LDA(data)

In [12]:
l.set_scatter_w_matrix()
l.set_scatter_b_matrix()

array([[374685.94 , 372050.75 , 373819.   , ..., -68872.234, -62483.73 ,
        -42925.5  ],
       [372050.75 , 369644.25 , 371359.3  , ..., -68169.77 , -61976.566,
        -43074.47 ],
       [373819.   , 371359.3  , 373299.38 , ..., -70224.4  , -63981.98 ,
        -44512.24 ],
       ...,
       [-68872.234, -68169.77 , -70224.4  , ..., 543062.94 , 556430.44 ,
        537296.7  ],
       [-62483.73 , -61976.566, -63981.98 , ..., 556430.44 , 588538.9  ,
        568147.7  ],
       [-42925.5  , -43074.47 , -44512.24 , ..., 537296.7  , 568147.7  ,
        554914.6  ]], dtype=float32)

In [24]:
l.get_lda(2)

(4096, 2)


array([[[-2.08747659e+01+0.j,  2.14402111e+01+0.j],
        [-2.08747659e+01+0.j,  2.14402111e+01+0.j],
        [-2.08747659e+01+0.j,  2.14402111e+01+0.j],
        [-2.08747659e+01+0.j,  2.14402111e+01+0.j],
        [-2.08747659e+01+0.j,  2.14402111e+01+0.j],
        [-2.08747659e+01+0.j,  2.14402111e+01+0.j],
        [-2.08747659e+01+0.j,  2.14402111e+01+0.j],
        [-2.08747659e+01+0.j,  2.14402111e+01+0.j],
        [-2.08747659e+01+0.j,  2.14402111e+01+0.j],
        [-2.08747659e+01+0.j,  2.14402111e+01+0.j]],

       [[-1.29652306e+01+0.j,  1.45677098e+01+0.j],
        [-1.29652306e+01+0.j,  1.45677098e+01+0.j],
        [-1.29652306e+01+0.j,  1.45677098e+01+0.j],
        [-1.29652306e+01+0.j,  1.45677098e+01+0.j],
        [-1.29652306e+01+0.j,  1.45677098e+01+0.j],
        [-1.29652306e+01+0.j,  1.45677098e+01+0.j],
        [-1.29652306e+01+0.j,  1.45677098e+01+0.j],
        [-1.29652306e+01+0.j,  1.45677098e+01+0.j],
        [-1.29652306e+01+0.j,  1.45677098e+01+0.j],
        [-

In [90]:
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis

lda = LinearDiscriminantAnalysis(n_components=2)

lda.fit(train_data, train_label)
iris_lda = lda.transform(train_data)


/Users/kim-seung-gyeom/opt/anaconda3/envs/ml/lib/python3.9/site-packages/sklearn/utils/validation.py:1111: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [ ]:
# import pandas as pd
#
# lda_columns=['lda_component_1','lda_component_2']
# irisDF_lda = pd.DataFrame(iris_lda, columns=lda_columns)
# irisDF_lda['target']=iris.target
#
# markers=['^', 's', 'o']
#
# for i, marker in enumerate(markers):
#     x_axis_data = irisDF_lda[irisDF_lda['target']==i]['lda_component_1']
#     y_axis_data = irisDF_lda[irisDF_lda['target']==i]['lda_component_2']
#
#     plt.scatter(x_axis_data, y_axis_data, marker=marker,label=iris.target_names[i])
#
# plt.legend(loc='upper right')
# plt.xlabel('lda_component_1')
# plt.ylabel('lda_component_2')
# plt.show()

In [23]:
import numpy as np

class CustomLDA:
    def fit(self, X, y):
        # 클래스별 샘플 평균 계산
        unique_classes = np.unique(y)
        mean_vectors = [np.mean(X[y == c], axis=0) for c in unique_classes]

        # 클래스 간 산포 행렬과 클래스 내 산포 행렬 계산
        S_W = np.zeros((X.shape[1], X.shape[1]))
        S_B = np.zeros((X.shape[1], X.shape[1]))
        overall_mean = np.mean(X, axis=0)
        for c, mean_vec in zip(unique_classes, mean_vectors):
            class_scatter = np.dot((X[y == c] - mean_vec).T, X[y == c] - mean_vec) / 10
            S_W += class_scatter
            n = X[y == c].shape[0]
            mean_diff = (mean_vec - overall_mean).reshape(-1, 1)
            S_B += n * np.dot(mean_diff, mean_diff.T)
        print(S_W)
        raise 100

        print(S_B)
        # 고유값 분해
        eigen_values, eigen_vectors = np.linalg.eig(np.dot(np.linalg.inv(S_W), S_B))

        # 고유값과 고유벡터를 내림차순으로 정렬
        idx = eigen_values.argsort()[::-1]
        eigen_values = eigen_values[idx]
        eigen_vectors = eigen_vectors[:, idx]

        # 클래스 간 분산과 클래스 내 분산의 고유벡터 선택
        num_components = min(len(unique_classes) - 1, 40)  # 최대 40개의 주성분 선택
        self.w = eigen_vectors[:, :num_components].real



    def transform(self, X):
        return np.dot(X, self.w)

# 사용 예시
# CustomLDA 모델 초기화
custom_lda = CustomLDA()
print(train_data.shape)
# 데이터에 모델 적용
# y_combined = np.hstack((np.zeros(len(x1)), np.ones(len(x2)), 2 * np.ones(len(x3))))  # 클래스 레이블 생성

# LDA 모델 훈련
custom_lda.fit(train_data, train_label.reshape(-1))
#
# 데이터를 저차원으로 투영
# x_lda_custom = custom_lda.transform(x_combined)[:,0]
# x_lda_custom

(370, 4096)
[[ 5968.07  5919.96  5763.33 ...  1004.59   240.66   540.29]
 [ 5919.96  6127.66  5909.57 ...   817.01   344.26   597.32]
 [ 5763.33  5909.57  5918.67 ...  1003.89   573.12   924.18]
 ...
 [ 1004.59   817.01  1003.89 ... 21738.95 14151.06 11214.05]
 [  240.66   344.26   573.12 ... 14151.06 17225.65 12951.77]
 [  540.29   597.32   924.18 ... 11214.05 12951.77 15884.37]]


TypeError: exceptions must derive from BaseException